import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'npm:@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Initialize Supabase client
const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const supabase = createClient(supabaseUrl, supabaseServiceKey);

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Verify authentication
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      return new Response(
        JSON.stringify({ error: 'Authentication required' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log('Starting sprite sheet generation...');

    // Ensure bucket exists (create if it doesn't)
    const { data: buckets } = await supabase.storage.listBuckets();
    const bucketExists = buckets?.some(b => b.id === 'hotdog-sprites');
    
    if (!bucketExists) {
      console.log('Creating hotdog-sprites bucket...');
      const { error: bucketError } = await supabase.storage.createBucket('hotdog-sprites', {
        public: true,
        fileSizeLimit: 10485760 // 10MB
      });
      if (bucketError) {
        console.error('Error creating bucket:', bucketError);
        throw bucketError;
      }
      console.log('Bucket created successfully');
    }

    // 1. Fetch all hotdogs from database
    const { data: hotdogs, error: fetchError } = await supabase
      .from('hotdogs')
      .select('id, city, latitude, longitude')
      .order('id');

    if (fetchError) {
      console.error('Error fetching hotdogs:', fetchError);
      throw fetchError;
    }

    console.log(`Found ${hotdogs?.length || 0} hotdogs to process`);

    if (!hotdogs || hotdogs.length === 0) {
      return new Response(
        JSON.stringify({ error: 'No hotdogs found' }),
        { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // 2. Calculate grid layout (8x8 = 64 slots for up to 64 hotdogs)
    const SPRITE_SIZE = 256; // Each hotdog sprite is 256x256
    const GRID_SIZE = 8; // 8x8 grid
    const SHEET_SIZE = SPRITE_SIZE * GRID_SIZE; // 2048x2048

    console.log(`Using ${GRID_SIZE}x${GRID_SIZE} grid (${SHEET_SIZE}x${SHEET_SIZE}px total)`);

    // 3. Generate sprite using Lovable AI Gateway
    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY not found');
    }

    // Create a canvas-like layout prompt for the AI
    const spritePrompt = `Create a ${SHEET_SIZE}x${SHEET_SIZE}px sprite sheet with a ${GRID_SIZE}x${GRID_SIZE} grid layout. Each cell is ${SPRITE_SIZE}x${SPRITE_SIZE}px and contains a photorealistic, transparent hotdog image from a different city/style. Include variety: Chicago dog, New York dog, Coney Island, Detroit coney, chili dog, corn dog, currywurst, etc. All hotdogs should be centered in their grid cell, viewed from 45-degree angle, with transparent background. Ultra high resolution, consistent style across all sprites.`;

    console.log('Generating sprite sheet with AI...');

    const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash-image-preview',
        messages: [
          {
            role: 'user',
            content: spritePrompt
          }
        ],
        modalities: ['image', 'text']
      })
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error('AI Gateway error:', errorText);
      throw new Error(`AI Gateway failed: ${aiResponse.status} - ${errorText}`);
    }

    const aiData = await aiResponse.json();
    const generatedImageBase64 = aiData.choices?.[0]?.message?.images?.[0]?.image_url?.url;

    if (!generatedImageBase64) {
      throw new Error('No image generated by AI');
    }

    console.log('Sprite sheet generated successfully');

    // 4. Upload sprite sheet to storage
    const base64Data = generatedImageBase64.replace(/^data:image\/\w+;base64,/, '');
    const imageBuffer = Uint8Array.from(atob(base64Data), c => c.charCodeAt(0));
    
    const version = Date.now();
    const fileName = `hotdog-sprite-v${version}.png`;

    console.log(`Uploading sprite sheet as ${fileName}...`);

    const { data: uploadData, error: uploadError } = await supabase.storage
      .from('hotdog-sprites')
      .upload(fileName, imageBuffer, {
        contentType: 'image/png',
        cacheControl: '31536000', // 1 year cache
        upsert: true
      });

    if (uploadError) {
      console.error('Upload error:', uploadError);
      throw uploadError;
    }

    console.log('Sprite sheet uploaded successfully');

    // 5. Get public URL
    const { data: urlData } = supabase.storage
      .from('hotdog-sprites')
      .getPublicUrl(fileName);

    const spriteSheetUrl = urlData.publicUrl;
    console.log('Sprite sheet URL:', spriteSheetUrl);

    // 6. Update database with sprite coordinates
    console.log('Updating hotdog sprite coordinates...');

    const updates = hotdogs.map((hotdog, index) => {
      const row = Math.floor(index / GRID_SIZE);
      const col = index % GRID_SIZE;
      
      return {
        id: hotdog.id,
        sprite_x: col * SPRITE_SIZE,
        sprite_y: row * SPRITE_SIZE,
        sprite_width: SPRITE_SIZE,
        sprite_height: SPRITE_SIZE,
        sprite_sheet_version: version,
        needs_sprite_update: false
      };
    });

    // Update in batches
    for (const update of updates) {
      const { error: updateError } = await supabase
        .from('hotdogs')
        .update({
          sprite_x: update.sprite_x,
          sprite_y: update.sprite_y,
          sprite_width: update.sprite_width,
          sprite_height: update.sprite_height,
          sprite_sheet_version: update.sprite_sheet_version,
          needs_sprite_update: update.needs_sprite_update
        })
        .eq('id', update.id);

      if (updateError) {
        console.error(`Error updating hotdog ${update.id}:`, updateError);
      }
    }

    console.log('All hotdog coordinates updated successfully');

    return new Response(
      JSON.stringify({
        success: true,
        spriteSheetUrl,
        version,
        hotdogsProcessed: hotdogs.length,
        gridSize: GRID_SIZE,
        spriteSize: SPRITE_SIZE,
        sheetSize: SHEET_SIZE
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error generating sprite sheet:', error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});