// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-hotdogs.ts
import { createClient } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_hotdogs_default = defineTool({
  name: "list_hotdogs",
  title: "List hotdogs",
  description: "List hotdogs in the Hotdog World catalog. Returns name, slug, city, country, and short description. Use `limit` (default 50) to page results.",
  inputSchema: {
    limit: z.number().int().positive().max(200).optional().describe("Max hotdogs to return (default 50, max 200)."),
    country: z.string().optional().describe("Optional country filter (case-insensitive substring).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, country }) => {
    const supabase = createClient(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = supabase.from("hotdogs").select("name, slug, city, country, description, region, tags").order("name", { ascending: true }).limit(limit ?? 50);
    if (country) q = q.ilike("country", `%${country}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { hotdogs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-hotdog.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_hotdog_default = defineTool2({
  name: "get_hotdog",
  title: "Get hotdog",
  description: "Get the full details for one hotdog by slug: ingredients, instructions, origin story, nutrition, trivia, and flavor profile.",
  inputSchema: {
    slug: z2.string().min(1).describe("Hotdog slug, e.g. 'chicago-style-hot-dog'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = createClient2(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("hotdogs").select("*").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No hotdog found with slug '${slug}'.` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { hotdog: data }
    };
  }
});

// src/lib/mcp/tools/search-hotdogs.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var search_hotdogs_default = defineTool3({
  name: "search_hotdogs",
  title: "Search hotdogs",
  description: "Search hotdogs by keyword across name, city, country, and description. Returns matching hotdogs with slug and short description.",
  inputSchema: {
    query: z3.string().min(1).describe("Search term, e.g. 'mustard', 'Tokyo', 'spicy'."),
    limit: z3.number().int().positive().max(100).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = createClient3(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const like = `%${query}%`;
    const { data, error } = await supabase.from("hotdogs").select("name, slug, city, country, description").or(`name.ilike.${like},city.ilike.${like},country.ilike.${like},description.ilike.${like}`).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { hotdogs: data ?? [], query }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yjpohmmrjuphbjjgvyhv";
var mcp_default = defineMcp({
  name: "hotdog-world-mcp",
  title: "Hotdog World",
  version: "0.1.0",
  instructions: "Tools for exploring the Hotdog World catalog \u2014 a curated atlas of hotdogs from around the globe. Use `search_hotdogs` to find hotdogs by keyword, `list_hotdogs` to browse (optionally by country), and `get_hotdog` to fetch full recipe, origin, nutrition, and trivia for a specific slug.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_hotdogs_default, get_hotdog_default, search_hotdogs_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
